<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enter card details</name>
   <tag></tag>
   <elementGuidId>fde73ea7-4007-4c3b-ac56-e25bb255e12f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pp-55TH3Z-119']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pp-55TH3Z-119</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5acd725e-eb21-41e8-94e7-f58502f4bdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-55TH3Z-119</value>
      <webElementGuid>3e0449d4-00d3-4f97-af09-57adb3b61053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-emphasis pmts-add-cc-default-trigger-link</value>
      <webElementGuid>c15d0754-c115-482b-9fdd-194668432f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5ad50c4c-49c2-4872-bb22-b41ec54de883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter card details</value>
      <webElementGuid>a3fd9a21-8f5d-438c-bcd3-36ab2e7872bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-55TH3Z-119&quot;)</value>
      <webElementGuid>9c646603-2a65-424f-9cc7-722c63b1951c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pp-55TH3Z-119']</value>
      <webElementGuid>e6fdbb3e-00f9-4d59-ac53-107abb44bdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='apx-add-credit-card-action-test-id']/div/a</value>
      <webElementGuid>12f9bc6c-9293-4ccd-a380-7f74cc88897e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enter card details')]</value>
      <webElementGuid>e7276f74-91cf-403d-97a6-cadc6cfd2216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>3b396ff2-2a62-4f25-9e7e-8219a2e6bdd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a</value>
      <webElementGuid>625c36c3-9fc7-4a41-b643-45677bba9992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pp-55TH3Z-119' and @href = '#' and (text() = 'Enter card details' or . = 'Enter card details')]</value>
      <webElementGuid>387ea222-ecd6-4803-b806-2d75c8d51655</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
