<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_ApxSecureIframe</name>
   <tag></tag>
   <elementGuidId>15cc8131-f9d6-4be8-8659-3f3a5f052f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='pp-55TH3Z-120']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pp-55TH3Z-120</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b234d78c-75b8-4355-8672-37e39ab6671d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-55TH3Z-120</value>
      <webElementGuid>a15df244-1ed5-4a64-9014-7893d8f6ed5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apx-secure-iframe pmts-portal-component pmts-portal-components-pp-55TH3Z-23</value>
      <webElementGuid>e24aedf3-a762-4936-8f18-10ad81e1c520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApxSecureIframe</value>
      <webElementGuid>9cdef89a-3a42-44dc-b600-596971fe66b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-55TH3Z-120&quot;)</value>
      <webElementGuid>e3ba869b-7f71-4628-b753-26e650a3e3aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='pp-55TH3Z-120']</value>
      <webElementGuid>681411a3-f158-49fe-bb5f-b60d55d35016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-55TH3Z-115']/div/div/div/div/div[2]/iframe</value>
      <webElementGuid>1774a60a-c69e-49f8-bf99-bb3878066bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>79c72f05-d5f6-4c7c-a923-56945748f46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'pp-55TH3Z-120' and @name = 'ApxSecureIframe']</value>
      <webElementGuid>8be0d61c-4fc3-4566-a09e-20b0a6290f4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
