<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ppw-instrumentRowSelection</name>
   <tag></tag>
   <elementGuidId>c33382a9-0bad-4396-92b6-9b7e2d423c60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-55TH3Z-116']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pp-55TH3Z-116</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8130038d-0d52-4f70-aded-416859fb43f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-55TH3Z-116</value>
      <webElementGuid>2eca85ff-b0e4-4ea8-a0c4-ae3a7eeb8aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>62a41d6b-7024-4478-9eab-a5f65ada4136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>1f89ced1-75b9-4c2a-858a-7815a06f411a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SelectableAddCreditCard</value>
      <webElementGuid>f70ed8cc-5635-4943-ae95-4bd4e20cb729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-55TH3Z-116&quot;)</value>
      <webElementGuid>d71619a4-2fff-4292-96ee-8cca1de458af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-55TH3Z-116']</value>
      <webElementGuid>4861e759-5897-49a2-b4b7-98f9cb657f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-55TH3Z-115']/div/div/div/div/div/span/div/label/input</value>
      <webElementGuid>132def4e-73b2-4c3f-b00e-636c2291e5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/span/div/label/input</value>
      <webElementGuid>ff5652cb-6713-4931-a44c-1c5b307efdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-55TH3Z-116' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>bdb8159b-cbf2-4d0d-8f5d-792c9e63d2b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
