<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ppw-widgetEventAddCreditCardEvent</name>
   <tag></tag>
   <elementGuidId>ee256080-8e07-4426-8741-db2ca7adc0fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ppw-widgetEvent:AddCreditCardEvent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ppw-widgetEvent:AddCreditCardEvent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6785ba71-1ea6-450f-a536-6a4159f4e12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-widgetEvent:AddCreditCardEvent</value>
      <webElementGuid>5b329387-f823-4686-9ff1-64b78f1020e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>fac8fdc1-9939-414a-b48a-60a0d05307b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8e13dc78-c59b-4b2b-8c76-26bd4a09d88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>pp-SFLzez-26-announce</value>
      <webElementGuid>22739610-662b-4d6d-a75c-cb06d6db6eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-SFLzez-26&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>601b9e03-7a4f-49fc-8c47-879d8c56c8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Amazon Payment Page/Validate_Amazon_Payment_Page_010/Page_Amazon.in Checkout/iframe_ApxSecureIframe</value>
      <webElementGuid>77d24216-49f0-4a45-b6f5-1df92cbe0e15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ppw-widgetEvent:AddCreditCardEvent']</value>
      <webElementGuid>a22b0766-0fb7-43d3-9fcd-0cfeb9179499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pp-SFLzez-26']/span/input</value>
      <webElementGuid>0036b1cd-3911-4c29-b0dc-8151718a6649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>a112f14e-b828-4820-9022-65759967667d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ppw-widgetEvent:AddCreditCardEvent' and @type = 'submit']</value>
      <webElementGuid>e066f43e-adfb-4b69-8bcb-56e3b512c6ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
