<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_addCreditCardNumber</name>
   <tag></tag>
   <elementGuidId>7d5f94bf-cd36-42f6-b47a-e9dc2dea117f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-SFLzez-16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pp-SFLzez-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a98e7f3f-f820-46d0-a5ba-7da18806268d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>3575e694-f087-4c1f-9e45-58381742f8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-SFLzez-16</value>
      <webElementGuid>9533ce54-e5f6-4376-93aa-701021c16aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b0b6a6e0-8f8f-4dac-9e8d-a1c25886635d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addCreditCardNumber</value>
      <webElementGuid>07584548-b3f1-4964-b065-f43d0cfeb35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bcc7f845-77e0-4344-98b5-5b698e0325ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-form-normal pmts-account-Number</value>
      <webElementGuid>d032507e-5fb8-4a27-8579-72eaba310040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-SFLzez-16&quot;)</value>
      <webElementGuid>381d7105-9b35-491d-9f7b-082746a7cf8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Amazon Payment Page/Validate_Amazon_Payment_Page_010/Page_Amazon.in Checkout/iframe_ApxSecureIframe</value>
      <webElementGuid>79ace48c-3a78-4fa9-b291-8271d0835706</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-SFLzez-16']</value>
      <webElementGuid>b3125488-5624-4d59-af20-f52b3934059d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='pp-SFLzez-14']/div/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>5ec16199-c691-4fbc-9584-be826b55fdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>316db618-aa1e-414c-8bed-3bd15923033f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'pp-SFLzez-16' and @name = 'addCreditCardNumber']</value>
      <webElementGuid>b0954979-7f22-49d8-a0da-8d3d2856d3c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
