<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.add-to-cart</name>
   <tag></tag>
   <elementGuidId>e52698e0-38ee-4615-93ef-b8efce7ada79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-to-cart-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-to-cart-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6304d94a-b2b6-444a-905d-d4ff9a9a700c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-cart-button</value>
      <webElementGuid>cb4ef8e3-2485-4dd5-82dc-3c0604e8c629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.add-to-cart</value>
      <webElementGuid>a2b941ed-bcfb-4f30-92c0-53a176a8ef67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add to Shopping Cart</value>
      <webElementGuid>d5ace71a-b1f4-4e76-a8f8-1a816045362d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>Select &lt;b>__dims__&lt;/b> from the left&lt;br> to add to Shopping Cart</value>
      <webElementGuid>469372c9-6de3-48db-924b-b647b8e995e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>d182e384-dc33-4258-a34f-5b3613487c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c5cd47b3-c428-4ed0-b145-e21ff064aa25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>fce14fe2-6e8f-4cbd-a456-f685525b40a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>submit.add-to-cart-announce</value>
      <webElementGuid>2aed3b4b-21d9-4038-9d30-fa5dfe06f236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formaction</name>
      <type>Main</type>
      <value>/cart/add-to-cart/ref=dp_start-bbf_1_glance</value>
      <webElementGuid>25304550-dae8-4262-b6cb-e6d8e594d83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-cart-button&quot;)</value>
      <webElementGuid>8355bc0a-b61e-44ff-bd4d-d5c55c536212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-to-cart-button']</value>
      <webElementGuid>78e82b11-3477-424b-9cd2-922f7880e787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='submit.add-to-cart']/span/input</value>
      <webElementGuid>806284d5-531e-4d95-a40c-de2b24ed2543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span/span/input</value>
      <webElementGuid>41330a5e-afe8-411b-ae77-4ce7893fb6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'add-to-cart-button' and @name = 'submit.add-to-cart' and @title = 'Add to Shopping Cart' and @type = 'submit']</value>
      <webElementGuid>a5ae221a-595a-4d76-b210-0f8c1b4c621e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
