<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1        2        3        4</name>
   <tag></tag>
   <elementGuidId>4dd3a9b2-20f4-4005-abf2-aeeea81370b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='quantity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quantity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>09a2f475-aeed-429d-abb3-0c0e62df2764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>88c36439-ff2b-4ba2-a93a-01357fa3cc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9efc7f64-469c-4392-ad1e-2a14d2b9c1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>40f14706-71a3-486c-9cd6-d10a23d21685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4b7f45b4-f9fa-4b89-8bba-d8c14290f519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>a-dropdown-select</value>
      <webElementGuid>910566ed-9f5b-47b6-b32f-40a37a271af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-native-dropdown a-declarative</value>
      <webElementGuid>53805e29-9012-4aa9-84aa-d237bf605419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     1        2        3        4             </value>
      <webElementGuid>7923a9fc-e555-4359-8b4a-cdc2262ee0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity&quot;)</value>
      <webElementGuid>1498b0d9-c5c0-4acc-b34d-658440dbf232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='quantity']</value>
      <webElementGuid>d3c3203a-51a4-4d25-af06-0fb7551c1f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectQuantity']/span/div/div/span/select</value>
      <webElementGuid>265f71cf-b66a-420d-85a8-d2d52865c147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/select</value>
      <webElementGuid>000fae18-c100-4984-9387-27c35ccadc54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'quantity' and @id = 'quantity' and (text() = '     1        2        3        4             ' or . = '     1        2        3        4             ')]</value>
      <webElementGuid>070355d6-a763-49a1-8db7-5439a0e4ab8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
