<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_in</name>
   <tag></tag>
   <elementGuidId>252524fa-4671-4a01-a120-8179d91a5f16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-logo-sprites</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-logo-sprites']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>909d667f-3167-4aba-a878-829a9606a5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ref=nav_logo</value>
      <webElementGuid>0f015d6b-b243-4d49-9fb9-f254c6c50738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-logo-sprites</value>
      <webElementGuid>9f9942a2-66d2-4f0f-ac67-4588c7bd7c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-logo-link nav-progressive-attribute</value>
      <webElementGuid>37f2f384-1a2e-44b9-ab16-5d56aff350c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Amazon.in</value>
      <webElementGuid>75619467-7475-4b83-8353-16d8ef061134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      
      
      .in
    </value>
      <webElementGuid>1e24e61c-55aa-479a-9252-5c5a0c2570e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-logo-sprites&quot;)</value>
      <webElementGuid>65ee2fa2-b19b-4ece-8e1d-8f9e75911186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-logo-sprites']</value>
      <webElementGuid>5032fe2a-2e30-42ef-a60d-cc1598afff2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-logo']/a</value>
      <webElementGuid>1522c35d-1d05-409a-b976-38a8fee39d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ref=nav_logo')]</value>
      <webElementGuid>dcc20a47-883d-44f0-a238-b56688d475b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>93fb57e3-bb37-4411-8ecd-c30d7733dcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ref=nav_logo' and @id = 'nav-logo-sprites' and (text() = '
      
      
      .in
    ' or . = '
      
      
      .in
    ')]</value>
      <webElementGuid>9c9ec1d4-b9ba-410a-87a0-c06f6b1c4852</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
