<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_imgSwatch</name>
   <tag></tag>
   <elementGuidId>7647c67d-9af5-4e1d-b637-59b52af6ffbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='a-autoid-14-announce']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a-autoid-14-announce > div > div > img.imgSwatch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ccfc97e-66d4-474f-90aa-665951d0d754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/41E9rFU0SYL._SX38_SY50_CR,0,0,38,50_.jpg</value>
      <webElementGuid>04ffb0e5-5a2d-4015-876f-cc172d1d057f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Light Blue</value>
      <webElementGuid>28111f0f-a52d-439a-a64f-497227b64463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgSwatch</value>
      <webElementGuid>8c2ac359-972f-431a-954d-23e90d0a47a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-14-announce&quot;)/div[1]/div[1]/img[@class=&quot;imgSwatch&quot;]</value>
      <webElementGuid>31cdb4ed-5633-408e-b983-42883d03cbfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='a-autoid-14-announce']/div/div/img</value>
      <webElementGuid>9ff39375-695a-43fb-accd-04b6008d1614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Light Blue']</value>
      <webElementGuid>9f86cd30-eba7-4154-b182-66b8ac98a2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span/div/span/span/span/button/div/div/img</value>
      <webElementGuid>7c5cd069-2ed8-48ce-bc38-e298bd2c2577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/I/41E9rFU0SYL._SX38_SY50_CR,0,0,38,50_.jpg' and @alt = 'Light Blue']</value>
      <webElementGuid>58063671-62f0-4954-8974-30c79afaeafb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
