<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select                     26       _e02b23</name>
   <tag></tag>
   <elementGuidId>52d5399c-b687-4181-9881-4d3e7e9d4358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='native_dropdown_selected_size_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#native_dropdown_selected_size_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fc916068-c443-465c-a179-8ec5cdbf8c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dropdown_selected_size_name</value>
      <webElementGuid>6dce9c2a-8d1c-485a-9286-28eca0c67290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d0d746c7-d718-4f57-9156-bd4d619d59ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-touch-header</name>
      <type>Main</type>
      <value>Size</value>
      <webElementGuid>b2614f9a-85aa-4473-948b-69ce83ce0452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>native_dropdown_selected_size_name</value>
      <webElementGuid>e2134613-ded0-40cc-9c18-6b62ee6c1e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ffdeff72-5428-4fc8-8477-c3ff5a65b828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>a-dropdown-select</value>
      <webElementGuid>c3d7fe0c-70b1-4ca2-86c2-28f4bae22dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-native-dropdown a-declarative</value>
      <webElementGuid>0cec545b-2bb9-4f46-abce-f7a71a418ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>      Select                     26             28             30             32             34             36   </value>
      <webElementGuid>8d0fe2df-eb11-42c7-bd52-dd101cca7246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;native_dropdown_selected_size_name&quot;)</value>
      <webElementGuid>48f1d3c9-04fb-40f8-88ab-e7b8d800985e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='native_dropdown_selected_size_name']</value>
      <webElementGuid>d5698092-06e5-4e27-bc63-1134d1aac481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='variation_size_name']/span/span/select</value>
      <webElementGuid>79cce3ba-5a96-4b5a-b141-6d709339d8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/select</value>
      <webElementGuid>86ab1e69-1c61-4fb9-b3bf-9e5657b35cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'dropdown_selected_size_name' and @id = 'native_dropdown_selected_size_name' and (text() = '      Select                     26             28             30             32             34             36   ' or . = '      Select                     26             28             30             32             34             36   ')]</value>
      <webElementGuid>98ee5e2d-f37c-4d90-9273-75d1f9a66bf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
