<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select                     26       _848e51</name>
   <tag></tag>
   <elementGuidId>a6d3d2cf-8eec-4c7c-a4a9-19b99f5c8383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='native_dropdown_selected_size_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#native_dropdown_selected_size_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f1ead656-efc8-47d6-b04d-7c0dec60a8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dropdown_selected_size_name</value>
      <webElementGuid>c632d6ff-7768-4c1e-9a6e-c0351a630fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2124a962-b454-4f83-9e03-4a7cfb8adf42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-touch-header</name>
      <type>Main</type>
      <value>Size</value>
      <webElementGuid>9ed676d9-2047-4d37-ad48-6b66f5fe8de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>native_dropdown_selected_size_name</value>
      <webElementGuid>72437260-bf8d-4cb1-8caa-160f9510a660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9096692b-78dc-4752-82b4-6413f3394e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>a-dropdown-select</value>
      <webElementGuid>ca521311-2174-4e16-89ce-e8202507ccac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-native-dropdown a-declarative</value>
      <webElementGuid>7d5f46ca-63c9-4886-a152-7bc2fb9ded12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>      Select                     26             30             32             34   </value>
      <webElementGuid>bac31f65-6a50-4bc2-949f-44caaf2aaf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;native_dropdown_selected_size_name&quot;)</value>
      <webElementGuid>de84768e-b4e1-4b15-9af6-752b705f2cbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='native_dropdown_selected_size_name']</value>
      <webElementGuid>8f1f3503-055f-4d7e-b32a-c250be81b687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='variation_size_name']/span/span/select</value>
      <webElementGuid>c61b160f-d9ce-4ccf-a3db-36bfcd356f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/select</value>
      <webElementGuid>8878c0bf-c971-4710-975d-e0a69844c292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'dropdown_selected_size_name' and @id = 'native_dropdown_selected_size_name' and (text() = '      Select                     26             30             32             34   ' or . = '      Select                     26             30             32             34   ')]</value>
      <webElementGuid>b452e6e1-56c3-4b2d-bc12-1e9c39e3d51f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
