<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submissionURL</name>
   <tag></tag>
   <elementGuidId>eb7cbe3f-76ab-478d-9438-e66bd317ca28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submissionURL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submissionURL&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44d7611d-de96-467a-86a8-7dc1a5816c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9303604b-f087-4ee7-96ad-4ca975a588a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submissionURL</value>
      <webElementGuid>005b48e4-c978-4828-802a-4b41c718eef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/checkout/p/p-404-9129943-1522723/address/shiptodestination/ref=chk_addr_select_1_customer?_encoding=UTF8&amp;abBusinessGroupId=&amp;action=select-shipping&amp;addressID=4LJLOLWBJXTQTPYFDJFEG1271LI65BV1WA3JW1VB56IL173PXTQ2EIA2OXYKGRIA&amp;enableDeliveryPreferences=1&amp;fromAnywhere=0&amp;numberOfDistinctItems=1&amp;purchaseId=404-9129943-1522723&amp;requestToken=</value>
      <webElementGuid>5f19a18a-bc94-43b0-a77c-5827af9f1dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-list&quot;)/div[@class=&quot;a-box-group a-spacing-small&quot;]/div[@class=&quot;a-box&quot;]/div[@class=&quot;a-box-inner&quot;]/fieldset[1]/div[@class=&quot;a-row address-row list-address-selected&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;a-radio&quot;]/label[1]/input[1]</value>
      <webElementGuid>da2de6c5-953c-4054-937b-a8230142a10a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submissionURL']</value>
      <webElementGuid>93eb8682-d0f6-458e-a8eb-5456d6b42703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address-list']/div/div/div/fieldset/div/span/div/label/input</value>
      <webElementGuid>37837456-90dc-40a9-be42-10f7d16eea50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>8b132717-9d77-460f-a7b4-f47ab17f5c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'submissionURL']</value>
      <webElementGuid>5fcd53e2-c621-4e15-b6cb-12444958ddf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
