<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_address-ui-widgets-enterAddressCity</name>
   <tag></tag>
   <elementGuidId>95fb1151-37f1-478c-889f-dc0410d1cbe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-ui-widgets-enterAddressCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-enterAddressCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c863df6e-a1da-430d-9bc6-291157222d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bef8fcf3-45d3-43f9-93cc-06b1c442d33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>9d098fe4-a31f-4edf-a753-fb34027665b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressCity</value>
      <webElementGuid>b43422aa-7247-4f81-9bcc-97ec4945c42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressCity</value>
      <webElementGuid>6a9f6b94-946f-4cec-bb8f-bdd7f6a74d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>117b84fc-8299-4f8f-8793-0d0cd76b4e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text address-ui-widgets-desktop-form-field-full-width addrui-form-text-input</value>
      <webElementGuid>0386c916-a098-428f-8f31-eafd530180e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressCity</value>
      <webElementGuid>07d2f7f0-2614-466b-8244-7bb86ce2272a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Town/City</value>
      <webElementGuid>ee43fe76-abd6-49b7-979e-5badbcf02a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressCity&quot;)</value>
      <webElementGuid>e05dccb3-8aaf-47b7-a401-cb32744cf339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-ui-widgets-enterAddressCity']</value>
      <webElementGuid>ea2f7532-6e44-4c82-9fdd-b2dc32476d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[7]/div/div[15]/div/div[2]/input</value>
      <webElementGuid>1d767fbf-6ddc-4076-a183-e87a8ab06288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/input</value>
      <webElementGuid>7597e107-b181-4574-ba01-a9165c27965e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address-ui-widgets-enterAddressCity' and @name = 'address-ui-widgets-enterAddressCity']</value>
      <webElementGuid>856fa8f2-c402-46e8-8602-9faa46ad447b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
