<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AbeBooksBooks, art collectibles</name>
   <tag></tag>
   <elementGuidId>4e4e8a1f-f467-4692-af7c-c6f30d4a42a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.navFooterDescItem > a.nav_a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div[5]/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f1d68ea-0e1f-400b-8f45-c5f115acf09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.abebooks.com/</value>
      <webElementGuid>045a332a-6d81-4e2b-87a0-2c2b0d485c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>60ea6ba8-9586-4399-bd4b-9b4e6f14b159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AbeBooksBooks, art&amp; collectibles</value>
      <webElementGuid>2f1d88f9-8ba8-4d4e-ab62-232fe3135d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterLine navFooterLinkLine navFooterDescLine&quot;]/table[@class=&quot;navFooterMoreOnAmazon&quot;]/tbody[1]/tr[1]/td[@class=&quot;navFooterDescItem&quot;]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>0849252e-28c5-4717-9cd0-8b5a85235b33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[5]/table/tbody/tr/td/a</value>
      <webElementGuid>37208c59-617c-49e0-bba1-9d97650d78ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.abebooks.com/')]</value>
      <webElementGuid>29c4bf14-cb9b-4a13-93e9-7f8e4638ff5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>69c73fdf-2c79-4102-b9b6-fe1d8066815a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.abebooks.com/' and (text() = 'AbeBooksBooks, art&amp; collectibles' or . = 'AbeBooksBooks, art&amp; collectibles')]</value>
      <webElementGuid>38822e0f-f634-41bc-af5b-5b1443a17f3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
