<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ShopbopDesignerFashion Brands</name>
   <tag></tag>
   <elementGuidId>a48e7224-802e-4179-a57f-a7e5d1c8929e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.navFooterDescItem > a.nav_a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div[5]/table/tbody/tr[3]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ab5fd86-f791-491b-afcc-4109ec494b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.shopbop.com/</value>
      <webElementGuid>23d0fbae-e8d1-437f-b465-40b04c9b1043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>db49c1fb-d690-4a47-aa96-eb1efea10522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ShopbopDesignerFashion Brands</value>
      <webElementGuid>247cfd56-783f-4ab8-bfc2-6babc2c7f059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterLine navFooterLinkLine navFooterDescLine&quot;]/table[@class=&quot;navFooterMoreOnAmazon&quot;]/tbody[1]/tr[3]/td[@class=&quot;navFooterDescItem&quot;]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>f7e7d429-09e2-47da-a826-9dd395ea3f68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[5]/table/tbody/tr[3]/td/a</value>
      <webElementGuid>87107362-79ab-4582-9235-88b28709a6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.shopbop.com/')]</value>
      <webElementGuid>af3471a6-038e-4d5d-a144-161af20de607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/a</value>
      <webElementGuid>5d9f68ad-e48d-4b22-905a-6b5ecadd5bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.shopbop.com/' and (text() = 'ShopbopDesignerFashion Brands' or . = 'ShopbopDesignerFashion Brands')]</value>
      <webElementGuid>964a44f2-c9d5-442d-8ba0-33b6703a4d28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
